services:
  service11:
    build:
      context: ./service_1  
      dockerfile: Dockerfile  
    container_name: service1
    ports:
      - "8001:8001"
    networks:
      - project

  service12:
    build:
      context: ./service_2  
      dockerfile: Dockerfile  
    container_name: service2
    ports:
      - "8002:8002"
    networks:
      - project    

  nginxx:
    build:
      context: ./nginx        
      dockerfile: Dockerfile  
    container_name: nginx-base
    ports:
      - "8080:80"
    depends_on:
      - service11
      - service12
    networks:
      - project

networks:
  project:
    driver: bridge